import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { LayoutTransition } from "@/components/global/layout-transition";
import { DisableDraft } from "@/components/global/disable-draft";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex gap-4 items-center justify-center">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
        </header>
        <SanityLive />
        <LayoutTransition>
          {children}
        </LayoutTransition>
        <VisualEditing />
      </body>
    </html>
  );
}
